# Generated by Django 5.0.6 on 2024-08-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolteam',
            old_name='age',
            new_name='ages',
        ),
        migrations.RenameField(
            model_name='schoolteam',
            old_name='gender',
            new_name='genders',
        ),
        migrations.RenameField(
            model_name='schoolteam',
            old_name='sport',
            new_name='sports',
        ),
    ]
