# Generated by Django 5.0.6 on 2024-08-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_age_athlete_ages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='ages',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='genders',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='athlete',
            old_name='sports',
            new_name='sport',
        ),
    ]
